# Copyright Rob Gage 2025

[package]
name = "pups_core"
version = "0.1.10"
license = "MIT"
description = "Pretty Understandable Parsers"
readme = "../README.md"
repository = "https://github.com/rob-gage/pups"
edition = "2024"

[dependencies]